version: "3.9"
services:
  mongo_database:
    image: mongo:latest
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - "${MONGO_DB_PORT}:27017"

  postgres_database:
    image: postgres
    container_name: postgres-container
    environment:
      - POSTGRES_DB=${PG_DB_NAME}
      - POSTGRES_USER=${PG_DB_USERNAME}
      - POSTGRES_PASSWORD=${PG_DB_PASSWORD}
    expose:
      - ${PG_DB_PORT}
    ports:
      - ${PG_DB_PORT}:5432
